import Foundation

/// Translates a FilterPolicy into pf rules for the packet-filter backend (used when the Network Extension
/// filter isn't available). pf works on addresses and ports, not apps, so:
///  - rules apply to whichever app uses that destination;
///  - app-specific rules for "any destination" use the addresses Bastion has learned for them;
///  - lockdown blocks new outbound TCP handshakes. The app stays in SYN-SENT, Bastion sees it, asks the
///    user, and an approval adds a pass rule so the next SYN retry gets through.
enum PFRules {
    static let anchor = "com.apple/250.Bastion"

    static func generate(_ policy: FilterPolicy, now: Date = Date()) -> String {
        var tables: [String] = []
        var blocks: [String] = []
        var passes: [String] = []

        func target(_ r: Rule) -> String? {
            if r.host == "*" && (r.appKey == "*" || r.direction == .inbound) { return "any" }
            var ips = r.addresses
            if isIP(r.host) { ips.insert(r.host, at: 0) }
            ips = Array(Set(ips.filter { isIP($0) && !$0.contains("%") })).sorted()
            guard !ips.isEmpty else { return nil }
            let name = "b\(tables.count)"
            tables.append("table <\(name)> const { \(ips.joined(separator: " ")) }")
            return "<\(name)>"
        }

        for r in policy.rules where (r.expires.map { $0 > now } ?? true) && r.proto != .other {
            let proto = r.proto.map { "proto \($0.rawValue)" } ?? "proto { tcp udp }"
            let port = r.port.map { "port \($0)" } ?? ""
            guard let t = target(r) else { continue }
            let line: String
            switch (r.verdict, r.direction) {
            case (.deny, .outbound): line = "block return out quick \(proto) from any to \(t) \(port)"
            case (.deny, .inbound): line = "block drop in quick \(proto) from \(t) to any \(port)"
            case (.allow, .outbound): line = "pass out quick \(proto) from any to \(t) \(port) keep state"
            case (.allow, .inbound): line = "pass in quick \(proto) from \(t) to any \(port) keep state"
            }
            if r.verdict == .deny { blocks.append(line) } else { passes.append(line) }
        }

        var out = ["# Generated by Bastion. Edits are overwritten.", "pass quick on lo0 all"]
        out += tables
        out += blocks
        if policy.lockdown {
            out += [
                "pass out quick proto udp from any to any port { 53 67 123 5353 } keep state",
                "pass out quick proto tcp from any to any port 53 keep state",
                "pass in quick proto udp from any to any port { 68 5353 }",
                "pass quick proto { icmp icmp6 } all",
            ]
            out += passes
            out += [
                "block drop out quick proto tcp all flags S/SA",
                "block drop out quick proto udp all",
                "block drop in quick proto tcp all flags S/SA",
                "block drop in quick proto udp all",
            ]
        }
        return out.map { $0.trimmingCharacters(in: .whitespaces) }.joined(separator: "\n") + "\n"
    }

    static func isIP(_ s: String) -> Bool {
        var v4 = in_addr(), v6 = in6_addr()
        return inet_pton(AF_INET, s, &v4) == 1 || inet_pton(AF_INET6, s, &v6) == 1
    }
}

/// Exported by the privileged helper (root LaunchDaemon). Only the signed Bastion app may connect.
@objc protocol HelperXPC {
    func ping(reply: @escaping (String) -> Void)
    /// JSON FilterPolicy → pf anchor. Replies nil on success or the pfctl error.
    func apply(policy: Data, reply: @escaping (String?) -> Void)
    /// Flushes the anchor and releases pf.
    func clear(reply: @escaping (String?) -> Void)
}

extension BastionIDs {
    static let helperLabel = "com.omarcharrkas.bastion.helper"
}
